# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 856a93bdeac9cd0c1eccd3f0788995fae87cb0b8968a2f6ffc671eac32464f45ba3253e8f6cc1ee17fbda7c2aaea8cfea107161e5ea4447a720b91243a01a4b3

test:
  secret_key_base: 043ff4437e3fc8f821372eef8d907a69b6a4dda83ff77c33834c4de9320f66d00b071512987c3ebfd058d36d43f3e056dfa322280c902aa4de8d9ac8ec4eca40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
